const words = [
    "Cup",
    "Dick",
    "Naniko",
    "Word",
    "Flash",
    "Suck",
    "Hypothalamus",
    "Brain",
    "Mode",
    "PoPApp",
    "Tits",
    "Rosa",
    "PurpleBit",
    "Hungry",
    "RockNRoll",
    "TV",
    "Python",
    "Nuke",
    "Bazera",
    "Chigla",
    "MineRoblox",
    "Nein Shtefan",
    "ARDESTO",
    "Jack Daniels",
    "Red Label",
    "Levi",
    "Turkey",
    "Spang",
    "KartoShka",
    "Gio",
    "Potato",
    "Void",
    "Sword",
    "Golden Apple",
    "Iphone",
    "ViVo",
    "Laptop",
    "K1kva",
    "Sub",
    "Smilga",
    "twoSum",
    "Chicken",
    "Cow",
    "F4ck Russia",
    "Shameless",
    "Nicshe",
    "React poop",
    "Sharlock",
    "JortSoft",
    "TazoTabaxis Furceli",
    "hardWork",
    "TomMato",
    "FuLA Calypse <3",
    "SLAVA",
    "Bismillah",
    "Jesus",
    "Brain1",
    "Lorenco xD",
    "DogStyle",
    "Fridge",
    "Microwave",
    "YT>",
    "PH",
    "Lambo",
    "BMVV",
    "KFCxD",
    "RandomWord4321",
    "Alahh",
    "Nugo",
    "Valdo",
    "NaniKO",
    "Salo",
    "Tika",
    "Saloou",
    "Qwertyuiop",
    "LastSecond",
    "CamelCase",
    "Qebab-case",
    "HTML>CSS",
    "YlNovatori",
    "UNIVERSSAL",
    "Optimus",
    "Thanos",
    "SpiderGela",
    "Apple",
    "Banana",
    "Cherry",
    "Date",
    "Elderberry",
    "Gig",
    "Grape",
    "Honeydew",
    "Kiwi",
    "Lemon",
    "Mango",
    "Orange",
    "Pear",
    "Quince",
    "Raspberry",
    "Strawberry",
    "Tangerine",
    "Watermelon",
    "Tkinter",
    "Lemonade",
    "Pubg",
    "Shawarma"
];

export default words